### ISSUE TITLE
Code review 1

### ISSUE THREAD

**Issue by kailynangelo** [shanda-matc/Expenses#3]
# Design/Code Review 1

### Reviewer: Kailyn Angelo

| Item | Considerations | Comments/Suggestions |

|--------|---------|---|

| Reviewer comments and suggestions go here. Each item should have
*at least* one "kudos" and two suggestions for improvement|

|**Problem Statement**| 1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| |

Very cool idea! I think this sounds like an interesting website. One area for improvement would be to elaborate on the solution more - explaining how will the user interact with it/what can they do in a little more detail. Another thing would be to clarify "different categories for writers and readers" - does this mean different options for writers/readers? Are there going to be different types of accounts depending on which one?

|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | |

I saw an application flow .md document in Design Documents folder but didn't see anything come up? The form design and overall application design look logical and easy to understand and use. One thing to improve would be to be more specific on, for example, the homepage. There are empty boxes under categories - what are these going to be? Another thing is the write story page - I see there is a category selection dropdown, then what looks like a free text box for content. Will the user write their entire story there? Will the input change based on the category they select? For example, could there be different character limits, prompts, or fields available depending on the story type selected?  

|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| |

Database includes everything from problem statement and one to many relationships are included. An idea for improvement would be to add to the Category table design - adding different properties such as character limit, other defining feature or even just a description could be useful. Another thing could be for the comments table adding user id as a foreign key to know who is leaving the comment. 

|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverage.

Good start on the project structure. A next step for structure could be adding folders to separate out the main src code so having java classes, resources/properties files, and then webapp/jsps all in their own folders. Then, generating unit tests for java classes.  

I thought it was really cool that you mentioned during code review that you are designing something that your kids will be able to use! I look forward to seeing your project!

**Comment by pawaitemadisoncollege** [comment]
Hi @kailynangelo! Your feedback here shows you've paid attention to giving both kudos and considerations for improvement in the various categories.  This is good evidence for the "provides meaningful feedback" competency. 

I did notice the markdown table formatting here is off a bit. This issue would be easier to read by either 1) fixing the formatting so the table renders correctly, OR remove the pipes so that no table notation is included.
